# Generated by Django 3.1.5 on 2021-01-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=200)),
                ('slug', models.CharField(help_text='Название на английском', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа', max_length=200)),
                ('slug', models.CharField(help_text='Название на английском', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название Мероприятия', max_length=200)),
                ('slug', models.CharField(help_text='Название на английском', max_length=200)),
                ('subject', models.TextField(help_text='Описание', max_length=5000)),
                ('picture', models.ImageField(help_text='Картинка', upload_to='images/')),
                ('link', models.CharField(help_text='Ссылка на мероприятие', max_length=200)),
                ('create_date_time', models.DateTimeField(auto_now=True, help_text='Дата и время создания')),
                ('start_date_time', models.DateTimeField(auto_now=True, help_text='Дата и время начала')),
                ('end_date_time', models.DateTimeField(auto_now=True, help_text='Дата и время конца')),
                ('tags', models.TextField(help_text='Тэги', max_length=1000)),
                ('place', models.TextField(help_text='Координаты места (для карты)', max_length=100)),
                ('adress', models.TextField(help_text='Адресс', max_length=100)),
                ('estimates', models.IntegerField(help_text='Колво-оценок')),
                ('count_estimates', models.IntegerField(help_text='Колво-оценок')),
                ('payed', models.BooleanField(default=False, help_text='Оплачено')),
                ('moderated', models.BooleanField(default=True, help_text='Модерация пройдена?')),
                ('category', models.ForeignKey(help_text='Категория', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category')),
                ('type', models.ForeignKey(help_text='Тип', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.type')),
            ],
        ),
    ]
