# Generated by Django 3.1.5 on 2021-01-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='renew',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время обновления'),
        ),
        migrations.AlterField(
            model_name='event',
            name='adress',
            field=models.TextField(help_text='Адрес', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date_time',
            field=models.DateTimeField(help_text='Дата и время конца'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date_time',
            field=models.DateTimeField(help_text='Дата и время начала'),
        ),
    ]
