# Generated by Django 3.1.5 on 2021-01-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210106_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='estimates',
            field=models.IntegerField(blank=True, help_text='Оценка', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Название мероприятия', max_length=200),
        ),
    ]
